### ISSUE TITLE
loginservice 400 (Bad Request)

### ISSUE THREAD

**Issue by gdegani** [astik/bonita-angular-dashboard-selfcontain#1]
Hello, 
I'm trying the dashboard as explained in the README, but when I try to login I see the following error into the browser console:
POST http://0.0.0.0:9000/bonita/loginservice 400 (Bad Request)

This is my context: 
-  Bonita Community Portal 7.2  started on http://localhost:8080/bonita
- app started with grunt serve:http://localhost:8080/bonita 

Have you any hint please ?

**Comment by astik** [comment]
It's been a while since I worked on this POC, I'll do my best =P
The README seems to be wrong. Grunt separate arguments with ":", this means that when you're writing :

```
grunt serve:http://localhost:8080/bonita
```

grunt spit the serve argument in 3 arguments.

If you trigger the server with just "grunt serve", you'll get an error which fix the README :

```
proxyTarget should be set : grunt serve:"http\\://PATH_TO_BONITA_SERVER\\:PORT
```

(see https://github.com/astik/bonita-angular-dashboard-selfcontain/blob/master/Gruntfile.js#L330)

So in your case :

```
grunt serve:"http\\://0.0.0.0\\:9000/bonita"
```

Hope that helps.

**Comment by gdegani** [comment]
Hi, 
thank you for your swift answer. 

I started grunt with the command:
 grunt -v -d serve:"http://localhost:8080/bonita" 

and something have changed...

At the moment the login works and I'm able to reach  the dashboard, but only with Firefox :-(
With Chrome I am redirected to a new page:
Navigated to http://localhost:9000/
angular.js:11086 user is not logged and access is restricted : redirecting to personal settings (/login)
angular.js:11086 BonitaAuthentication.login success
Navigated to https://www.google.it/_/chrome/newtab?espv=2&ie=UTF-8

and the same happens with Safari. 

Thank you for your help.

**Comment by astik** [comment]
If my memory is right, you'll need to escape the ":" in your URL in the grunt CLI with double slashes : "\:".

I can not work on this project for now as I have no free time =(
I will try to find some time as soon as possible to fix this issue with chrome and clean the doc.
In the meantime, feel free to contribute and PR =P
